<script setup>
const props = defineProps({
    order: Object
})

import { ref, onMounted } from 'vue'
const pdfContent = ref(null)
</script>
<template>
    <div ref="pdfContent" class="pdf-container">
        <div class="header">
            <h2>Order Details</h2>
        </div>
        <div class="body">
            <p><strong>Order No:</strong> {{ order.order_no }}</p>
            <p><strong>Design No:</strong> {{ order.design_no }}</p>
            <p><strong>Item:</strong> {{ order.item_name }}</p>
            <p><strong>Quantity:</strong> {{ order.quantity }}</p>
            <p><strong>Status:</strong> {{ order.status }}</p>
        </div>
        <div class="footer">
            Generated by Swati Textile ERP
        </div>
    </div>
</template>
